name: CI

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Luau LSP Version
        id: get_latest
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/JohnnyMorganz/luau-lsp/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Luau LSP Cache Restore
        id: cache-luau-lsp
        uses: actions/cache/restore@v5
        with:
          path: luau-lsp-bin
          key: luau-lsp-${{ env.LATEST_TAG }}

      - name: Setup Luau LSP (If Cached)
        if: steps.cache-luau-lsp.outputs.cache-hit == 'true'
        run: sudo cp luau-lsp-bin/luau-lsp /usr/local/bin/luau-lsp

      - name: Setup Luau LSP (If Not Cached)
        if: steps.cache-luau-lsp.outputs.cache-hit != 'true'
        run: |
          mkdir -p luau-lsp-bin
          curl -L -o luau-lsp-bin/luau-lsp.zip https://github.com/JohnnyMorganz/luau-lsp/releases/download/${{ env.LATEST_TAG }}/luau-lsp-linux-x86_64.zip
          unzip luau-lsp-bin/luau-lsp.zip -d luau-lsp-bin/
          chmod +x luau-lsp-bin/luau-lsp
          sudo cp luau-lsp-bin/luau-lsp /usr/local/bin/luau-lsp

      - name: Luau LSP Cache Save
        if: always()
        uses: actions/cache/save@v5
        with:
          path: luau-lsp-bin
          key: luau-lsp-${{ env.LATEST_TAG }}

      - name: Run Tests
        run: |
          perl -pi -e 's/require\("\@self"\)/require\("\.\/"\)/g' src/init.test.luau
          luau-lsp analyze --flag LuauSolverV2=true src/init.test.luau
        